### ISSUE TITLE
Email Loop when Queue address is in cc

### ISSUE THREAD

**Issue by SurtursRevenge** [django-helpdesk/django-helpdesk#825]
Hello,

we observed the following behaviour. When a client sends an email with the queue mail address in cc this email is added to the cc mails of the ticket resulting in a mail loop triggered by the confirmation email send out to all cc mails.
I think the queue mail address should be filtered out and not be added to the ticket cc list nor should mails be send to this mail

Best regards

**Comment by timthelion** [comment]
Which version of helpdesk are you using?

**Comment by SurtursRevenge** [comment]
At the moment we are using 0.2.19

**Comment by SurtursRevenge** [comment]
Any Update on this ? 
Do you need more information to reproduce the Issue ?

**Comment by Benbb96** [comment]
I did not reproduce this behavior on 0.2.21.

I send an email to queue mail address with this same address in CC. Then ticket get created but the queue mail address isn't added to TicketCC so it doesn't loop.

Maybe this issue was fixed in the following versions of 0.2.19 ?

**Comment by gwasser** [comment]
I believe there were some changes to CC in the recent bugfix releases. Let me know if you can reproduce or think this has been fixed. @SurtursRevenge please update to 0.2.21 if you can and let us know the result.

**Comment by ssedlmaier** [comment]
Hello,

I looked into this issue and it is not resolved yet.

The problem may partly be hidden or mitigated by the mail server. 
Exchange for example will delete the queue mail in the CC list if it is the recipient as well. So basically you need to send a mail to someone different with the queue in CC.

Furthermore there are basic checks which try to exclude the queue address here
https://github.com/django-helpdesk/django-helpdesk/blob/630cfd91793313266024baaabe1d036488e601c4/helpdesk/management/commands/get_email.py#L451-L455

This works basically but it does not take into account that e.g. "Support Mail <support@mail.com>" is a valid email which may be in the cc list extracted here
https://github.com/django-helpdesk/django-helpdesk/blob/630cfd91793313266024baaabe1d036488e601c4/helpdesk/management/commands/get_email.py#L319-L328

So if I have the queue email address support@mail.com and someone sends a mail to test@mail.com with "Support Mail <support@mail.com>" in the CC list the issue will occur.

To this point I only testet this with existing tickets. Not sure if this also occurs if creating a new one.

So to fix this cc and other_mails need to be normalized into some form. Unfortunately I am not familiar which mail address formats are valid, if there is already a function to do this and if this would have an impact on anything else.

I hope this helps to resolve this issue.

**Comment by uhurusurfa** [comment]
Probably fixed by this PR:
https://github.com/django-helpdesk/django-helpdesk/pull/1264
