### ISSUE TITLE
Date Range filter on ticket list doesn't work

### ISSUE THREAD

**Issue by Benbb96** [django-helpdesk/django-helpdesk#899]
When doing my PR #898, I tested filters and it appears that the date range was not respected under certain circonstances.

**To Reproduce**
1. Go to Ticket List
2. Add Date Range filter box
3. Add some values for From and To dates
4. Apply filter

**Expected behavior**
Tickets should be filtered by these dates.

**Screenshots**
![image](https://user-images.githubusercontent.com/15046586/98270063-c96b4680-1f8e-11eb-9efd-75a4c975d9f6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google chrome
 - Version: 86.0.4240.111

**Additional context**
I think there is a conflict with other filters (like the status) during the SQL query. **Because if I remove the status filter, it then works as expected**.

**Comment by shreyashsrivastava** [comment]
Is this issue still open? I want to work on it.

**Comment by gwasser** [comment]
As far as I know, this bug might still exist and needs addressed. Would appreciate your help checking it out and fixing it with a PR, @shreyashsrivastava !

**Comment by DavidVadnais** [comment]
Tested:
2022-01-01 2023-01-01
2022-01-01 ""
""                  2023-01-01

None of these work.

Then I noticed that changing the **Sorting** drop-down had no effect.  Interestingly the **Status(es):**  and **Owner** selection does work. 

When the filter or is removed then the queries work  in the query.py __run__

`queryset = queryset.filter((Q(**filter) | Q(**filter_or)) & self.get_search_filter_args())`

filter_or always returns 'status__in': [1, 2]

removing filter or does this fix but that is not likely the intended fix. I'm going to open a draft pull request seeking further clarification

**Comment by uhurusurfa** [comment]
The code surrounding this is somewhat obfuscated and difficuly to understand what the intended behaviour is since there are no comments.

The query you show above would work if the either of "filter" or "filter_or" had an empty dict but the code in helpdesk/views/staff.py has an initialiser for default filtering values:
```
    query_params = {
        'filtering': {},
        'filtering_or': {},
        'sorting': None,
        'sortreverse': False,
        'search_string': '',
    }
    default_query_params = {
        'filtering': {
            'status__in': [1, 2],
        },
        'sorting': 'created',
        'search_string': '',
        'sortreverse': False,
    }

```
This is why filter_or always returns 'status__in': [1, 2]. As a result of the default query values, both "filter" and "filter_or" will never be empty and the resultant query duplicates the exact same filter criteria most of the time which results in an inefficient query.
My guess is that the implementer intended to only use the "filter_or" for the case when trying to include fileds that are null.

So changing this in staff.py:
```
        for param, filter_command in filter_in_params:
            if request.GET.get(param) is not None:
                patterns = request.GET.getlist(param)
                try:
                    pattern_pks = [int(pattern) for pattern in patterns]
                    if -1 in pattern_pks:
                        query_params['filtering_or'][filter_null_params[param]] = True
                    else:
                        query_params['filtering_or'][filter_command] = pattern_pks
                    query_params['filtering'][filter_command] = pattern_pks
                except ValueError:

```
... to this:
```
        for param, filter_command in filter_in_params:
            if request.GET.get(param) is not None:
                patterns = request.GET.getlist(param)
                try:
                    pattern_pks = [int(pattern) for pattern in patterns]
                    if -1 in pattern_pks:
                        query_params['filtering_or'][filter_null_params[param]] = True
                    query_params['filtering'][filter_command] = pattern_pks
                except ValueError:

```
... might solve the issue.

**Comment by uhurusurfa** [comment]
This should be solved by #1241

**Comment by DavidVadnais** [comment]
After starting up the database using PostgreSQL 13 as described in issue #1230 I was still unable to sort the tickets out using data range. I tried having the date range before the tickets were made and after the tickets were made.

The logs printed the following warning:
```
django-helpdesk-1  |   warnings.warn(
django-helpdesk-1  | /usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py:1665: RuntimeWarning: DateTimeField Ticket.created received a naive datetime (2023-03-01 00:00:00) while time zone support is active.
```

My git commit running was:
```
git log

commit 07e5eff73e653710661e0d9a7c0406b64efcc408 (HEAD -> BUG-1230-postgresql-version-django-missmatch, origin/BUG-1230-postgresql-version-django-missmatch)
Author: DavidVadnais <david.vadnais@protonmail.com>
Date:   Fri Mar 7 14:09:38 2025 -1000

    standalone postgresql v12-->v13

commit 3a33f7fef9a00724bf8c351bef08e9f6867a4e1a (origin/main, origin/HEAD, main)
Merge: 836dc6c5 fb898af2
Author: Christopher Broderick <uhurusurfa@gmail.com>
Date:   Fri Mar 7 13:45:08 2025 +0000

    Merge pull request #1241 from django-helpdesk/ticket_query_fixes
    
    Ticket query fixes

commit fb898af20786e9f14a62e78dba5d3e0e864e702d
Author: Christopher Broderick <uhurusurfa@gmail.com>
Date:   Fri Mar 7 13:33:41 2025 +0000

    Fix spelling

commit abdd750e2aa0d294f93fc4cd5ac042c0735b4c5b
Author: Christopher Broderick <uhurusurfa@gmail.com>
Date:   Thu Mar 6 12:18:30 2025 +0000

    REvert status to not support unassigned since it is a required field.

commit e64490e20f6605ae25e472163168c6f44c3ea624
Author: Christopher Broderick <uhurusurfa@gmail.com>
Date:   Thu Mar 6 03:12:41 2025 +0000

    Bump version for a release
```

Here is a screen shot of the ranges I used:
![Image](https://github.com/user-attachments/assets/e8c9026f-6cb8-4103-b39f-beb02bc1b57c)

**Comment by uhurusurfa** [comment]
I cannot replicate an issue uising date filters.
Can you put this just before line 152 of the latest version of query.py to see what sort of query it has built please:
`print(f"BUILT QUERY: {queryset.query}")`

**Comment by DavidVadnais** [comment]
This is fixed. 

I got confused when running docker compose up it was pulling old version of the django-helpdesk image since updating our image is currently broken and it no longer by default builds the image locally.

**Comment by uhurusurfa** [comment]
Ok - will close this as #1244 should fix the docker build
